---
apiVersion: v1
kind: Namespace
metadata:
  name: internal-nginx
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: internal-nginx
  namespace: internal-nginx
spec:
  interval: 24h
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: internal-nginx
  namespace: internal-nginx
spec:
  interval: 30m
  chart:
    spec:
      chart: ingress-nginx
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: internal-nginx
        namespace: internal-nginx
      interval: 12h
  values:
    installCRDs: true
    controller:
      podAnnotations:
         prometheus.io/scrape: "true"
         prometheus.io/port: "10254"
      metrics:
        enabled: true
      service:
         annotations:
           meta.helm.sh/release-name: "ingress-nginx"
           prometheus.io/scrape: "true"
           prometheus.io/port: "10254"
    admissionWebhooks:
      enabled: false
