apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ext-podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      spec:
        ingressClassName: external-nginx
      hosts:
        - host: lab.corebits.ca
          paths:
            - path: /
              pathType: ImplementationSpecific
